# Generated by Django 2.2.2 on 2019-11-03 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helpyou', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='td_categoria',
            name='data_criacao',
        ),
    ]
